# echo -n 'SECRET_ID' | c2VjcmV0LXNob3ctYW5kLXRlbGw=
# echo -n 'SECRET_MESSAGE:' | U2hvdy1JbmtyaXMtR2F0ZXdheS1TZWNyZXQ=

---
# This creates a Secret that holds the environment variables
apiVersion: v1
kind: Secret
metadata:
  name: gatewaygenius-demo-secrets
  namespace: default
type: Opaque
data:
  secret_id: c2VjcmV0LXNob3ctYW5kLXRlbGw= #Should be base64 encoded and should come from the output of the command echo or CI/CD tool
  secret_message: U2hvdy1JbmtyaXMtR2F0ZXdheS1TZWNyZXQ= #Should be base64 encoded and should come from the output of the command echo or CI/CD tool
